application-local.ymlserver:
  #默认访问端口
  port: 8888
  #默认访问路径
  context-path: /basic-platform

#日志配置
logging:
  level: debug
  file: ./logs/base/base.log

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/base
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


